### ISSUE TITLE
IP address for Local Daikin is not set. Please provide 'ip_address' in the configuration.yaml.

### ISSUE THREAD

**Issue by pjgoodall** [Apoc182/local_daikin#18]
Hello,
Thanks for your efforts. This is all a bit new to me.  Worked through it with chatgpt 4o. Could not find any misconfigurations.
Cheers....

I got the ip address of my A/C from the Daikin app.
It is reachable, and if I open it using http I get a text about RTOS license.
it is reachable from the terminal of HA:
```
➜  config ping 192.168.0.191             
PING 192.168.0.191 (192.168.0.191): 56 data bytes
64 bytes from 192.168.0.191: seq=0 ttl=255 time=29.765 ms
64 bytes from 192.168.0.191: seq=1 ttl=255 time=45.768 ms
64 bytes from 192.168.0.191: seq=2 ttl=255 time=67.758 ms
^C
```
 
my configuration.yaml:
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

climate:
  - platform: local_daikin
    host: 192.168.0.191
```

logger:
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:366
integration: Climate (documentation, issues)
First occurred: 4:32:43 PM (1 occurrences)
Last logged: 4:32:43 PM

Error while setting up local_daikin platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/local_daikin/climate.py", line 148, in async_setup_platform
    raise ValueError("IP address for Local Daikin is not set. Please provide 'ip_address' in the configuration.yaml.")
ValueError: IP address for Local Daikin is not set. Please provide 'ip_address' in the configuration.yaml.
```

The local_daikin components are in place:
```
~ ls config/custom_components/local_daikin 
__init__.py    __pycache__    climate.py     manifest.json
```

**Comment by pjgoodall** [comment]
I have restarted and rebooted multiply

**Comment by ajvandr** [comment]
You need to use the naming scheme from the readme.  You have host instead of ip_address.

climate:
  - platform: local_daikin
    ip_address: X.X.X.Y

**Comment by Apoc182** [comment]
Hi @pjgoodall. As @ajvandr has suggested, that is the most likely your issue. Thanks.

**Comment by pjgoodall** [comment]
I did a remove and re-install with the configuration.yaml modifications already in place. The error is not logging now.

If this does not provide any useful information - am happy to close.
